"""empty message

Revision ID: 0c8a6629557a
Revises: 1c60640b95a0
Create Date: 2025-03-30 21:35:56.324049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c8a6629557a'
down_revision = '1c60640b95a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motion_audio_sync', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('custom_notes', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('audio_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('beat_timestamps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.drop_column('lip_sync_json')

    with op.batch_alter_table('motion_capture_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('beat_timestamps', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rigged_avatar_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rigged_avatar', ['rigged_avatar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motion_capture_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rigged_avatar_id')
        batch_op.drop_column('beat_timestamps')
        batch_op.drop_column('audio_filename')

    with op.batch_alter_table('motion_audio_sync', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lip_sync_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('beat_timestamps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('audio_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('custom_notes')
        batch_op.drop_column('song_name')

    # ### end Alembic commands ###
