"""empty message

Revision ID: 1622e2a95734
Revises: 0c8a6629557a
Create Date: 2025-04-03 02:03:59.497041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1622e2a95734'
down_revision = '0c8a6629557a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motion_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('frames', sa.JSON(), nullable=True),
    sa.Column('fx_timeline', sa.JSON(), nullable=True),
    sa.Column('export_date', sa.DateTime(), nullable=True),
    sa.Column('audio_filename', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exported_fbx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('export_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_outfit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('style', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_outfit')
    op.drop_table('exported_fbx')
    op.drop_table('motion_session')
    # ### end Alembic commands ###
