"""empty message

Revision ID: 1c60640b95a0
Revises: a42cb1b41f16
Create Date: 2025-03-30 19:06:45.508341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c60640b95a0'
down_revision = 'a42cb1b41f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_used_gb', sa.Float(), nullable=True),
    sa.Column('rigging_sessions', sa.Integer(), nullable=True),
    sa.Column('mocap_sessions', sa.Integer(), nullable=True),
    sa.Column('videos_rendered', sa.Integer(), nullable=True),
    sa.Column('render_minutes', sa.Float(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('skeleton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rigged_avatar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rigged_avatar_id'], ['rigged_avatar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('skeleton_id', sa.Integer(), nullable=False),
    sa.Column('offset_x', sa.Float(), nullable=True),
    sa.Column('offset_y', sa.Float(), nullable=True),
    sa.Column('offset_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['bone.id'], ),
    sa.ForeignKeyConstraint(['skeleton_id'], ['skeleton.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_plan')

    op.drop_table('bone')
    op.drop_table('skeleton')
    op.drop_table('user_usage')
    # ### end Alembic commands ###
