"""empty message

Revision ID: a42cb1b41f16
Revises: d72f0e0da3e0
Create Date: 2025-03-30 00:40:48.504713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42cb1b41f16'
down_revision = 'd72f0e0da3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dance_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_name', sa.String(length=100), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('beat_times', sa.JSON(), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motion_audio_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('audio_filename', sa.String(length=255), nullable=True),
    sa.Column('beat_timestamps', sa.JSON(), nullable=True),
    sa.Column('lip_sync_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motion_audio_sync')
    op.drop_table('dance_session')
    # ### end Alembic commands ###
